### ISSUE TITLE
services section

### ISSUE THREAD

**Issue by nysrinenajem** [FadiZahhar/caroleammoun#2]
I would like to add a margin top, margin left, margin right to the text please.
I would like it to be 30px each.

**Comment by FadiZahhar** [comment]
will visit you tomorrow at the office to inspect the element and do it together in case ok, will implement to the website.

**Comment by FadiZahhar** [comment]
this was fixed by adding the following code

```
@media screen and (max-width: 1200px) {
   .hgr_advimage a div {
        padding:2%!important;
    }
 }
```

in case you need to increment the percentage you can login to the back office , Appearance -> Theme Options -> custom code, the box that is realted to CSS

**Comment by nysrinenajem** [comment]
thank you fadi!
have a good day :)
